package view;

import model.dao.LivrosDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.beans.Livros;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author D-JTP
 */
public class TelaLivro extends javax.swing.JFrame {

 LivrosDao dao = new LivrosDao();

    /**
     * Creates new form TelaLivros
     */
    public TelaLivro() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        tblLivros.setRowSorter(new TableRowSorter(modelo));
        zerar();
    }
    
    // Campos da tabela com o livro selecionado
    private void setar_campos() {
        int setar = tblLivros.getSelectedRow();
        txtLivId.setText(tblLivros.getModel().getValueAt(setar, 0).toString());
        txtLivTitulo.setText(tblLivros.getModel().getValueAt(setar, 1).toString());
        txtLivAutor.setText(tblLivros.getModel().getValueAt(setar, 2).toString());
        txtLivAno.setText(tblLivros.getModel().getValueAt(setar, 3).toString());       
        txtLivUnidades.setText(tblLivros.getModel().getValueAt(setar, 4).toString());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLivTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLivAutor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLivUnidades = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtLivId = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtLivPesquisar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLivros = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtLivAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Livros");
        setMaximumSize(new java.awt.Dimension(522, 563));
        setMinimumSize(new java.awt.Dimension(522, 563));

        jLabel2.setText("Título:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cadastro de Livros");

        jLabel3.setText("Autor:");

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("*");

        jLabel5.setText("Unidades:");

        jLabel12.setText("ID:");

        txtLivId.setEditable(false);
        txtLivId.setText("0");
        txtLivId.setEnabled(false);

        btnRemover.setText("Excluir");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnAdicionar.setText("Cadastrar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("Campos obrigatórios possuem um (*)");

        txtLivPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLivPesquisarKeyReleased(evt);
            }
        });

        jLabel11.setText("Pesquisar por título:");

        tblLivros = new javax.swing.JTable() {
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Título", "Autor", "Ano", "Unidades"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLivros.setFocusable(false);
        tblLivros.getTableHeader().setReorderingAllowed(false);
        tblLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLivros);

        jLabel7.setText("Ano de Publicação:");

        txtLivAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLivAnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLivPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLivTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtLivUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLivAno, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addGap(190, 190, 190)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLivId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtLivAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdicionar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAlterar)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRemover)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLivTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLivAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtLivUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtLivId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtLivAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAlterar)
                    .addComponent(btnRemover))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLivPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // Metodo para remover o livro
        int confirma = JOptionPane.showConfirmDialog(null, "Quer mesmo excluir  o livro?", "Aviso", JOptionPane.YES_NO_OPTION);
        Livros liv = carregaLivros();
        if (confirma == JOptionPane.YES_OPTION) {
            if (dao.delete(liv)) {
                JOptionPane.showMessageDialog(null, "Livro excluído com sucesso");
                zerar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Metodo para alterar o livro
        Livros liv = carregaLivros();
        if ((txtLivId.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha o campo obrigatório");
        } else {
            if (dao.update(liv, Integer.valueOf(txtLivId.getText()))) {
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
                zerar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Metodo para cadastro do livro
        Livros liv = carregaLivros();
        if ((txtLivTitulo.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha o campo obrigatório");
        } else {
            if (dao.insert(liv)) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                zerar();
            } else {
                JOptionPane.showMessageDialog(null, "Erro");
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtLivPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLivPesquisarKeyReleased
        // Evento enquanto está digitando
        pesquisar();
    }//GEN-LAST:event_txtLivPesquisarKeyReleased

    private void tblLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLivrosMouseClicked
        // Evento para setar os campos da tabela no formulário
        setar_campos();
    }//GEN-LAST:event_tblLivrosMouseClicked

    private void txtLivAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLivAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLivAnoActionPerformed

    
    public Livros carregaLivros() {
        Livros liv = null;
        try {
            int idli = Integer.valueOf(txtLivId.getText());
            String tituloli = txtLivTitulo.getText();
            String autorli = txtLivAutor.getText();
            int anoli = 0;
            int unidadesli = 0;
            if (txtLivAno.getText().length() > 0) {
                anoli = Integer.valueOf(txtLivAno.getText());
            }
            if (txtLivUnidades.getText().length() > 0) {
                unidadesli = Integer.valueOf(txtLivUnidades.getText());
            }
            liv = new Livros(idli, tituloli, autorli, anoli, unidadesli);
        } catch (NumberFormatException erro) {
            System.out.println(erro);
            JOptionPane.showMessageDialog(null, "Erro");
        }

        return liv;
    }
    
    public void zerar() {
        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        modelo.setNumRows(0);
        
        txtLivId.setText("0");
        txtLivTitulo.setText(null);
        txtLivAutor.setText(null);
        txtLivAno.setText(null);
        txtLivUnidades.setText(null);
        txtLivPesquisar.setText(null);
        for (Livros liv : dao.select()) {
            modelo.addRow(new Object[]{
                liv.getId(),
                liv.getNome(),
                liv.getAutor(),
                liv.getAno(),
                liv.getUnidades()
            });
        }
        pesquisar();
    }

    private void pesquisar() {
        DefaultTableModel modelo = (DefaultTableModel) tblLivros.getModel();
        modelo.setNumRows(0);
        
        String titulo = txtLivPesquisar.getText();
            for (Livros liv : dao.selectFrom(titulo)) {
                modelo.addRow(new Object[]{
                   liv.getId(),
                    liv.getNome(),
                    liv.getAutor(),
                    liv.getAno(),
                    liv.getUnidades()
                });
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLivros;
    private javax.swing.JTextField txtLivAno;
    private javax.swing.JTextField txtLivAutor;
    private javax.swing.JTextField txtLivId;
    private javax.swing.JTextField txtLivPesquisar;
    private javax.swing.JTextField txtLivTitulo;
    private javax.swing.JTextField txtLivUnidades;
    // End of variables declaration//GEN-END:variables
}
